Parse single map definitions
Parse a map definition line into a `Map`.

Got so stuck on this error:

    error[E0277]: the trait bound `(): combine::Parser` is not satisfied
       --> src/lib.rs:107:16
        |
    107 | fn map<I>() -> impl Parser<Input = I, Output = Map>
        |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `combine::Parser` is not implemented for `()`
        |
        = note: the return type of a function must have a statically known size

    error: aborting due to previous error

    For more information about this error, try `rustc --explain E0277`.

Turns out the problem was that I had put a semicolon at the end of the
expression in `map()`. Geez. Took hours to finally see that.