run_key_action_for_mode(): Keep track of `in_mode` in `state`
Instead of letting the Objective-C code keep track of `in_mode` by
passing it around in `CKeyActionResult`, keep track of it in a `State`
struct.

Derive `Clone` on `HeadphoneButton` to resolve this error:

    error[E0277]: the trait bound `parser::HeadphoneButton: std::clone::Clone` is not satisfied
       --> src/cocoa_bridge.rs:273:38
        |
    273 |         state.in_mode = Some(trigger.to_vec());
        |                                      ^^^^^^ the trait `std::clone::Clone` is not implemented for `parser::HeadphoneButton`